### ISSUE TITLE
Suggestion: Split the __init__.py into multiple files

### ISSUE THREAD

**Issue by matthewhively** [larryhastings/starvote#1]
I would suggest for readability to re-organize the __init__.py file by moving distinct portions into other files.
Specifically:
- each voting method function moved into separately named file/module
- the helper methods moved into a helpers file/module (such as: `measure_int_or_fraction_as_str`)
- tiebreaker classes moved into a separate file

There are probably other ways the code could be segmented out into purpose built files, but this is my quick suggestion.

**Comment by larryhastings** [comment]
Thanks for your interest!  But I'm comfortable working with it all in one big file.  I don't see how readability would be improved by breaking starvote up into lots of little files.
