### ISSUE TITLE
marshal.dumps does not always produce identical results given inputs that compare equal

### ISSUE THREAD

**Issue by encukou** [larryhastings/starvote#10]
`marshal` output depends on internal object details. This can make the hash-based tie-breaking algorithm depend on the way the data was loaded, compiler optimizations, etc.
For example, there's string interning:
```py
import sys
import starvote

names = 'Amy', 'Brad', 'Chuck', 'Darcy', 'Ema', 'Fifi', 'Gabe', 'Honza', 'Ivan'

# Ballots with names given as string literals (implicitly interned)
first_ballots = [
    {name: 1 for name in names}
    for vote in range(5)
]

# Ballots with names that aren't interned
second_ballots = [
    {name.encode().decode(): vote for name, vote in ballot.items()}
    for ballot in first_ballots
]

assert first_ballots == second_ballots

for ballots in first_ballots, second_ballots:
    result = starvote.election(starvote.bloc, ballots, seats=2)
    print(result)

```
prints (on my system):
```
['Brad', 'Karel']
['Ema', 'Lumi']
```

Not sure if you're looking for solutions; if you are, I might suggest [a hand-written serializer](https://gist.github.com/encukou/1eb448906c247e7c2bdce9d9ac468e53) or [a canonical-only encoding](https://en.wikipedia.org/wiki/Bencode).

**Comment by larryhastings** [comment]
Huh.  How does interning interact with marshal serialization?

Is `pickle.dumps` deterministic, or is it similarly affected?

**Comment by encukou** [comment]
Marshal will reconstruct equivalent objects. A string's intern status is not guaranteed to be preserved; neither is an object's refcount (which can also affect the result, at least on some CPython versions).

I could not find a quick example for `pickle.dumps`, but it's definitely not guaranteed to be bit-for-bit equal for equivalent objects.
(Definitely not across Python versions. If you change the default, I'd recommend that you drop the requirement that you need the same Python build to reproduce the result.)

**Comment by larryhastings** [comment]
It's not letting me request you as a reviewer.  Would you mind doing the honors?

**Comment by encukou** [comment]
Sure!

While I'm here looking for references to `marshal`, I found a few details you might want to adjust:

> verbosity specifies how much output you want. The current supported values are 0 (no output) and 1 (output); values higher than 1 are currently equivalent to 1.

There's now a tie breaker that checks `verbosity >= 3`.

> Also, the only way to usefully control this algorithm is to control the seed value--and to do that you'd have to control all the ballots. And if you control all the ballots, you don't need to influence the tiebreaker! You can just change the votes to directly produce whatever outcome you prefer.

Yes, but: if you can *both* see all the ballots *and* change your own, you could fudge your ballot until you get the desired result.
