### ISSUE TITLE
Add blank lines to output for improved readability 

### ISSUE THREAD

**Issue by lordmauve** [larryhastings/starvote#2]
It would make it more readable if the printed output had blank lines to make it easier to distinguish the sections.

Readability is important as not everyone will be familiar with the process of tallying under STAR voting.

Alternatively or additionally, it might be cute if it produced valid Markdown which could be rendered as HTML...

**Comment by larryhastings** [comment]
I can look in to adding some blank lines.

In general, I was trying to make the output both computer-readable and human-readable.  I now think I wound up accomplishing neither particularly well.  If I was writing the library again, I'd make the default output a computer-readable text format, then add formatters for human-readable text, HTML, Markdown, etc.

**Comment by larryhastings** [comment]
I added a blank line before every section heading, as long as it wasn't the first line of output.
