### ISSUE TITLE
Feature Request - CSV with Options

### ISSUE THREAD

**Issue by masiarek** [larryhastings/starvote#4]
See details in video:  https://youtu.be/CYB-DoGJ1YY

**Comment by larryhastings** [comment]
I'm not going to watch your video in order to see your feature request.  Please summarize it here in text.

**Comment by masiarek** [comment]
Feature Request - allow CSV file to use the [options] syntax. 

Currently CSV works only with single winner and only with one voting method. 

Additionally, the first columns must be following format expected by www.star.vote 

Proposed logic: 

- allow CSV file to use the [options] syntax.

- example CSV file 

[options]
method = bloc
winners = 2
tiebreaker = none
verbosity = 1

[ballots]
A,B,C
5,2,4
1,0,5
5,4,0
4,2,5

**Comment by larryhastings** [comment]
Sorry, no.  CSV files have a very specific syntax, and is not extensible.  Reading CSV files is a surprisingly complicated process, fraught with incompatibilities and inconsistencies; unless you're familiar with the problem domain it's best to just use Python's csv module.  I don't want to write my own CSV reader, I just want to use the Python csv module like everybody else.

However, you can already achieve this feature with starvote.  Create your own ".starvote" file, and "include" your CSV file using the "csv_path" option in the "[options]" section.  You can then set options like "method" and "winners", which will override the default settings used for CSV files.  The CSV file itself still has to be in star.vote CSV format.

**Comment by masiarek** [comment]
Yes,  'csv_path' works like a charm.

Example file 'csv_test.starvote'

[options]

    csv_path = csv_test.csv
    method = sss
    seats = 3
    tiebreaker = none
    verbosity = 1

Example cvs file - 'csv_test.csv'

A,B,C,D,E
5,0,0,5,1
5,3,2,3,1
5,4,0,3,4

Result - works fine:
[Sequentially Spent Score]
  Tabulating 3 ballots.
  Maximum score is 5.
  Want to fill 3 seats.
  Hare score quota is 5.
[Sequentially Spent Score: Round 1]
  The highest-scoring candidate wins ed seat.
    A -- 15 (average 5)     -- First place
    D -- 11 (average 3+2/3)
    B --  7 (average 2+1/3)
    E --  6 (average 2)
    C --  2 (average 2/3)
  A wins ed seat.
[Sequentially Spent Score: Round 1: Ballot allocation round]
  Total score is 15, Hare score quota is 5, giving back surplus.
  Reducing each ballot's stars by their vote * 2/3.
  3 ballots voted 5, stars reduced from 5 to 10/3, reweighted to 2/3.
[Sequentially Spent Score: Round 2]
  The highest-scoring candidate wins ed seat.
    D -- 7+1/3 (average 2+4/9) -- First place
    B -- 4+2/3 (average 1+5/9)
    E -- 4     (average 1+1/3)
    C -- 1+1/3 (average 4/9)
  D wins ed seat.
[Sequentially Spent Score: Round 2: Ballot allocation round]
  Total score is 7+1/3, Hare score quota is 5, giving back surplus.
  Reducing each ballot's stars by their vote * 7/22.
  Reweighted 3 ballots:
     2 ballots voted 2, stars reduced from 10/3 to 65/33, reweighted to 13/33.
     1 ballot voted 10/3, stars reduced from 10/3 to 35/33, reweighted to 7/33.
[Sequentially Spent Score: Round 3]
  The highest-scoring candidate wins ed seat.
    B -- 2+25/33 (average 91/99) -- First place
    E -- 2+ 2/11 (average  8/11)
    C -- 26/33   (average 26/99)
  B wins ed seat.
[Sequentially Spent Score: Winners]
  A
  B
  D

**Comment by masiarek** [comment]
I had to comment out this line of code in method 'load_csv_file(path)'

row = row[3:]

Now the CSV file works as:

A,B,C,D,E
5,0,0,5,1
5,3,2,3,1
5,4,0,3,4
