### ISSUE TITLE
Number of Seats cannot be higher than Number of Candidates

### ISSUE THREAD

**Issue by masiarek** [larryhastings/starvote#6]
We get incorrect error message:
KeyError("'A'")

Instead of:
- Number of Seats cannot be higher than Number of Candidates.

How to reproduce the issue:

[options]

    method = sss
    seats = 5
    tiebreaker = None
    verbosity = 1

[ballots]

2 ballots:
A=5
B=4
C=0
D=0

A=0
B=4
C=0
D=5

**Comment by masiarek** [comment]
here is the complete output:

[Sequentially Spent Score]
  Tabulating 3 ballots.
  Maximum score is 5.
  Want to fill 5 seats.
  Hare score quota is 3.
[Sequentially Spent Score: Round 1]
  The highest-scoring candidate wins ed seat.
    B -- 12 (average 4)     -- First place
    A -- 10 (average 3+1/3)
    D --  5 (average 1+2/3)
    C --  0 (average 0)
  B wins ed seat.
[Sequentially Spent Score: Round 1: Ballot allocation round]
  Total score is 12, Hare score quota is 3, giving back surplus.
  Reducing each ballot's stars by their vote * 3/4.
  3 ballots voted 4, stars reduced from 5 to 4, reweighted to 4/5.
[Sequentially Spent Score: Round 2]
  The highest-scoring candidate wins ed seat.
    A -- 8 (average 2+2/3) -- First place
    D -- 4 (average 1+1/3)
    C -- 0 (average 0)
  A wins ed seat.
[Sequentially Spent Score: Round 2: Ballot allocation round]
  Total score is 8, Hare score quota is 3, giving back surplus.
  Reducing each ballot's stars by their vote * 5/8.
  2 ballots voted 4, stars reduced from 4 to 5/2, reweighted to 1/2.
[Sequentially Spent Score: Round 3]
  The highest-scoring candidate wins ed seat.
    D -- 4 (average 1+1/3) -- First place
    C -- 0 (average 0)
  D wins ed seat.
[Sequentially Spent Score: Round 3: Ballot allocation round]
  Total score is 4, Hare score quota is 3, giving back surplus.
  Reducing each ballot's stars by their vote * 1/4.
  1 ballot voted 4, stars reduced from 4 to 1, reweighted to 1/5.
[Sequentially Spent Score: Round 4]
  The highest-scoring candidate wins ed seat.
    C -- 0 (average 0) -- First place
  C wins ed seat.
[Sequentially Spent Score: Round 5]
  The highest-scoring candidate wins ed seat.
    A -- 5     (average 1+2/3) -- First place
    B -- 4+4/5 (average 1+3/5)
    D -- 1     (average 1/3)
    C -- 0     (average 0)
  A wins ed ?? seat.   ?????
KeyError("'A'")     <==

**Comment by larryhastings** [comment]
Good catch!  Fixed in 2.1.  Thanks for the bug report!
