### ISSUE TITLE
"No Preference" should be the number of voters who expressed no preference in a round, not the number of head-to-head contests where no preference was expressed in a round

### ISSUE THREAD

**Issue by masiarek** [larryhastings/starvote#7]
[options]

    method = star
    tiebreaker = none
    verbosity = 1

[ballots]

    Andre  = 5
    Blake  = 5
    Carmen = 5
    
    Andre  = 3
    Blake  = 3
    Carmen = 3

    Andre  = 4
    Blake  = 4
    Carmen = 4
    

[STAR Voting]
  Tabulating 3 ballots.
  Maximum score is 5.
[STAR Voting: Scoring Round]
  The two highest-scoring candidates advance to the next round.
    Andre  -- 12 (average 4) -- Tied for first place
    Blake  -- 12 (average 4) -- Tied for first place
    Carmen -- 12 (average 4) -- Tied for first place
  There's a three-way tie for first.
[STAR Voting: Scoring Round: First tiebreaker]
  The two candidates preferred in the most head-to-head matchups advance.
    Andre         -- 0 -- Tied for first place
    Blake         -- 0 -- Tied for first place
    Carmen        -- 0 -- Tied for first place
    No Preference -- 9
  There's still a three-way tie for first.
[STAR Voting: Scoring Round: Second tiebreaker]
  The two candidates with the most votes of score 5 advance.
    Andre  -- 1 -- Tied for first place
    Blake  -- 1 -- Tied for first place
    Carmen -- 1 -- Tied for first place
  There's still a three-way tie for first.
[STAR Voting: Scoring Round: Unbreakable Tie]
  Tie between Andre, Blake, and Carmen.

**Comment by larryhastings** [comment]
Thanks for pointing out the bug.  I had to figure out what you meant.  Here's my summary:

"No Preference" should be the number of *voters*
who expressed no preference between any of the candidates
in what I call a "preference round".  It was actually
printing the number of individual head-to-head contests
in the round that had no preference, and there could be
more than one on a single ballot.

**Comment by larryhastings** [comment]
Thanks for the bug report!  This was fixed in 2.1.
