### ISSUE TITLE
missing expected error message "specified candidate '...' twice on one ballot"

### ISSUE THREAD

**Issue by masiarek** [larryhastings/starvote#9]
Bug similar to issue 8 - starvote

File ‘example.py’
```
import starvote

ballots = [
    {'Amy': 1, 'Amy': 2},
    ]

winners = starvote.election(starvote.star, ballots, verbosity=1)
```

[STAR Voting]
 Tabulating 1 ballots.
 Maximum score is 5.

[STAR Voting: Scoring Round]
 The two highest-scoring candidates advance to the next round.
 Only one candidate, they win.

[STAR Voting: Winner]
 A

Problem:

- missing expected error message "specified candidate '...' twice on one ballot"

==
https://github.com/larryhastings/starvote/issues/8 - similar issue has been resolved here:
Issue number has been fixed - this works fine now ( we get expected error)
[options]
    method = star
    verbosity = 1

[ballots]
    5 ballots:
        Amy = 3
        Amy = 2

Expected error message is raised - great!:
“specified candidate 'Amy' twice on one ballot”

**Comment by larryhastings** [comment]
If you print `ballots`, you'll discover that Python itself has thrown away the redundant key-balue.  In this case `ballots` is simply `{'Amy': 2}`.

**Comment by larryhastings** [comment]
My first reply was a little off-the cuff; let me elaborate a little.

The Python `dict` object literally _can't_ store duplicate entries with the same key.  My buddy Brandon gave a famous, well-regarded talk on how the Python `dict` works internally, you might find it interesting:

https://www.youtube.com/watch?v=C4Kc8xzcA68

So, in your dict literal, the second assignment to the key `'Amy'` overwrites the first one.  Therefore, the first line of your example actually assigns the dict `{'Amy': 2}` to `ballots`.  starvote is working properly here.

I'm a little surprised that Python doesn't throw an exception in this case.  But I suspect it's 30-year-old behavior and can't be changed now.
